<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="PRG_Calibration" Id="{f2ab8e02-eb8c-441d-b1b0-c2b3833b2b19}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM PRG_Calibration
VAR_OUTPUT
    bCalibrationFinished : BOOL;  // Indica o fim com sucesso da calibração
END_VAR
VAR
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Reset" Id="{27813d8d-2df7-44d9-b974-4b44cba9f55d}">
      <Declaration><![CDATA[METHOD Reset : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="PRG_Calibration">
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="PRG_Calibration.Reset">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>