<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.13">
  <POU Name="FB_DryingPhase" Id="{3fed5c2e-00c0-41f9-b86a-23cb950cee48}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_DryingPhase

VAR_INPUT
END_VAR

VAR_OUTPUT
	bDryingDone : BOOL;
END_VAR

VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[//bDryingDone := (* Verdadeiro quando a etapa de secagem for concluída; ]]></ST>
    </Implementation>
    <LineIds Name="FB_DryingPhase">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>