<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.13">
  <POU Name="FB_HardwareInit" Id="{31780309-bb82-4307-91d5-5548f242181e}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_HardwareInit

VAR_INPUT
END_VAR

VAR_OUTPUT
	bHardwareOK : BOOL;
END_VAR

VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_HardwareInit">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>