<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="FB_WashingPhase" Id="{8cd1e697-bf8b-43c9-9f41-396622ef9579}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_WashingPhase

VAR_INPUT
END_VAR

VAR_OUTPUT
	bWashingDone 	: BOOL; 	//washing done flag
	bWashingError 	: BOOL;		//washing error flag
END_VAR

VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[//bWashingDone := //Verdadeiro quando a etapa de lavagem for concluída]]></ST>
    </Implementation>
    <LineIds Name="FB_WashingPhase">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>