<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="PRG_ReportsManager" Id="{425548c3-5dc9-40cc-99a5-02604507aa06}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM PRG_ReportsManager
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[// Calibration Reports


// AutoCycle Reports


// Pumps Reports

]]></ST>
    </Implementation>
    <LineIds Name="PRG_ReportsManager">
      <LineId Id="5" Count="0" />
      <LineId Id="7" Count="1" />
      <LineId Id="6" Count="0" />
      <LineId Id="10" Count="1" />
      <LineId Id="9" Count="0" />
      <LineId Id="13" Count="0" />
      <LineId Id="12" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>