<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="MAIN_Services" Id="{3af486fa-0c2d-4875-b9ea-bc50deddc50f}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN_Services
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="MAIN_Services">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>