<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="MAIN_HMI" Id="{3c91d346-e8aa-4b63-90ca-940de5bd825a}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN_HMI
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="MAIN_HMI">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>