<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="MAIN_Events" Id="{7a39f841-be4d-45aa-93ed-4769dfe66808}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN_Events
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="MAIN_Events">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>