<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_MCMoveRelative" Id="{0eb7de6a-89bd-45de-9b73-ee6b3d62cd32}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_MCMoveRelative EXTENDS MC_MoveRelative
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[//FB inherits every funcion from the parent class]]></ST>
    </Implementation>
    <LineIds Name="FB_MCMoveRelative">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>