{
  "controlTypeValues": {
    "TcHmi.Controls.Beckhoff.TcHmiButton": {
      "attributes": {
        "BackgroundColor": {
          "angle": 0.0,
          "stopPoints": [
            {
              "color": "rgba(89, 125, 156, 1)",
              "stop": "21.64%"
            },
            {
              "color": "rgba(32, 78, 119, 1)",
              "stop": "100%"
            }
          ]
        },
        "TextColor": {
          "color": "rgba(253, 253, 253, 1)"
        }
      },
      "themedResources": {}
    }
  },
  "controlClassValues": {},
  "$schema": "./../../../Git/Packages/Beckhoff.TwinCAT.HMI.Framework.12.762.44/runtimes/native1.12-tchmi/Schema/ThemeDescription.Schema.json"
}