<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="PRG_SystemInfo" Id="{3ecda4e7-3da9-4b19-a635-328f489eb573}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM PRG_SystemInfo
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="PRG_SystemInfo">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>