<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_ErrorHandler" Id="{ed3260d9-d359-4ae7-aa35-a2a28acdd00d}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_ErrorHandler

VAR_INPUT
END_VAR

VAR_OUTPUT
	bErrorResolved : BOOL;
END_VAR

VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[//bErrorResolved := (* Verdadeiro quando o erro for resolvido]]></ST>
    </Implementation>
    <LineIds Name="FB_ErrorHandler">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>