<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="F_sec_to_time" Id="{4eb65088-1bbd-4939-b718-6074c5176ced}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_sec_to_time : TIME
VAR_INPUT
	sec : LREAL;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[F_sec_to_time := LREAL_TO_TIME(MAX(0.0, sec) * 1000.0);]]></ST>
    </Implementation>
    <LineIds Name="F_sec_to_time">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>