<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="F_VolumeToSteps" Id="{25d1f51c-9d43-4775-9a00-54ad1198621b}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_VolumeToSteps : REAL
VAR_INPUT
	rVolume 		: REAL; // Volume in mL
    iPumpIndex 		: INT;  // Pump index 1..10
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[//Use individual calibration for each pump
F_VolumeToSteps := (rVolume / GVL_Motion.aPumps[iPumpIndex].Rotary.rPumpFactor) * 360;]]></ST>
    </Implementation>
    <LineIds Name="F_VolumeToSteps">
      <LineId Id="22" Count="0" />
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>